#!/bin/bash

while [ $# -gt 0 ] ; do
    if [[ -f "$1" ]] && [[ ! -L "$1" ]] ; then
        echo "backing up $1 to $1.bak"
        cp -piv "$1" "$1".bak
    elif [[ -d "$1" ]] ; then
        echo "skipping $1 as directory backup is not supported"
    elif [[ -e "$1" ]] ; then
        echo "skipping non-regular file $1"
    else
        echo "error: file $1 not found"
    fi
    shift
done
