#!/bin/bash

# get current time in format YYYY-MM-DD_HHMMSS-ZZZZ
# where ZZZZ is the numeric time zone (e.g. -0500)
_NOW=$(date -Is | sed -e 's/T/_/' -e 's/://g')

# return this value without the time zone section
currtime=${_NOW%-*}

create_dir() {
    
    if [[ -z "$1" ]] ; then
        mkdir "$currtime"
    else
        mkdir "$1"/"$currtime"
    fi
}


base_dir=""

while getopts :e OPT; do
    case $OPT in
        e) echo "$currtime"
            exit 0
            ;;
    	*)
            echo "usage: ${0##*/} [-e] [basedir]"
            exit 2
    esac

done
shift $(( OPTIND - 1 ))
OPTIND=1


[ $# -gt 0 ] && {
    base_dir="$1"
}

create_dir "$base_dir"
