#!/bin/bash

if (( $# == 0 )) || [[ "$1" =~ --?h(elp)? ]] ; then
	echo "Usage: $0 word [word]...
	Duplicates stdin to stdout with any occurrences
	of the specified words highlighted in red.
	"
	exit 0
fi

words=( $@ )

cRed='\\e[1;4;31m'
cOff='\\e[0m'
seds="sed "
i=0
for w in "${words[@]}"; do
    seds="${seds} -e s/$w/$cRed&$cOff/g; "
    let i+=1
done

# what.
echo -e "$($seds <&0)" # what is this.
# i don't even.

# ...how did i figure this one out?
