#!/bin/bash

DISABLE=( 'XHCI' 'EHC1' 'EHC2' )

disable_states() {
    for d in "${DISABLE[@]}";
    do
        state=$(cat /proc/acpi/wakeup | grep $d | cut -f3 | cut -d' ' -f1 | tr -d '*')
        #    echo "device = $d, state = $state"
        if [ "$state" == "enabled" ]
        then
            sudo sh -c "echo $d > /proc/acpi/wakeup"
        fi
    done
}

disable_states
